# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
  # main-list
    - staticcheck
    - deadcode
    - errcheck
    - gosimple
    - ineffassign
    - structcheck
    - typecheck
    - unused
    - varcheck
  # extra-list
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - interfacer
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - exportloopref
    - sqlclosecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace
   
disable:
  # main-list
    - govet
    - revive
    - stylecheck
   

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
