version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis-srv
    restart: always
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - cqt-net
    entrypoint: redis-server #/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-web
    hostname: redis-commander
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - cqt-net
    ports:
      - "8081:8081"
  
  node:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache-cli
    restart: always
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
    depends_on:
      - redis-commander
    networks:
      - cqt-net
    ports:
      - "8545:8545"

  cqt-virtnet:
    image: "ghcr.io/covalenthq/cqt-virtnet:latest"
    container_name: proof-chain
    restart: always
    depends_on:
      - node
    networks:
      - cqt-net
    tty:
      true
    ports:
      - "8008:8008"

  consumer:
    container_name: mq-store-agent
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - cqt-virtnet
    environment:
      - ETH_PRIVATE_KEY=0x22aabb811efca4e6f4748bd18a46b502fa85549df9fa07da649c0a148d7d5530
    networks:
      - cqt-net
    ports:
      - "8080:8080"

  # consumer-two:
  #   container_name: replication-consumer-two
  #   build: '.'
  #   environment:
  #     REDIS_HOST: redis
  #     STREAM: replication
  #     GROUP: replicate-2
  #   depends_on:
  #     - redis
  #   restart: always

networks:
  cqt-net: