name: docker-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bsp-agent-eth:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      if: ${{ !env.ACT }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}

    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Build & Publish the Docker image
      if: ${{ !env.ACT }}
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/covalenthq/bsp-agent:latest
        docker push ghcr.io/covalenthq/bsp-agent:latest

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - uses: actions/checkout@v2
    - name: Build & Publish the Docker image
      run: |
        docker buildx create --name builder --use --platform=linux/amd64,linux/arm64  && docker buildx build --platform=linux/amd64,linux/arm64 . -t gcr.io/covalent-project/bsp-agent:latest --push

    - name: Create .env file
      run: |
        touch .env
        echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
        echo RPC_URL=${{ secrets.RPC_URL }} >> .env
        cat .env

    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2

    - name: Run containers
      run: docker-compose -f "docker-compose-ci.yml" up --build --remove-orphans --exit-code-from agent

    - name: Check running agent
      run: docker inspect bsp-agent

    - name: Check running containers
      run: docker ps

    - name: Delete .env & bin files
      run: |
        rm -rf .env && rm -rf ./bin/block-ethereum

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down
  
  # bsp-agent-elrond:
  #   runs-on: ubuntu-latest
  #   env:
  #     BLOCKCHAIN: elrond
  #   steps:
  #   - name: Login to GitHub Container Registry
  #     if: ${{ !env.ACT }}
  #     uses: docker/login-action@v1
  #     with:
  #       registry: ghcr.io
  #       username: ${{ secrets.CR_USER }}
  #       password: ${{ secrets.CR_PAT }}

  #   - uses: actions/checkout@v2
  #   - name: Build & Publish the Docker image
  #     if: ${{ !env.ACT }}
  #     run: |
  #       docker build . --file Dockerfile --tag ghcr.io/covalenthq/bsp-agent:latest
  #       docker push ghcr.io/covalenthq/bsp-agent:latest

  #   - name: Create .env file
  #     run: |
  #       touch .env
  #       echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
  #       echo RPC_URL=${{ secrets.RPC_URL }} >> .env
  #       cat .env

  #   - name: Load .env file
  #     uses: xom9ikk/dotenv@v1.0.2

  #   - name: Start containers
  #     run: docker-compose -f "docker-compose-ci.yml" up --build --remove-orphans --exit-code-from agent

  #   - name: Check running agent
  #     run: docker inspect bsp-agent

  #   - name: Check running containers
  #     run: docker ps

  #   - name: Delete .env file & bin files
  #     run: |
  #       rm -rf .env && rm -rf ./bin/block-elrond

  #   - name: Stop containers
  #     if: always()
  #     run: docker-compose -f "docker-compose-ci.yml" down

