name: docker-image-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-eth:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      if: ${{ !env.ACT }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}

    - uses: actions/checkout@v2
    - name: Build & Publish the Docker image
      if: ${{ !env.ACT }}
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/covalenthq/bsp-agent:latest
        docker push ghcr.io/covalenthq/bsp-agent:latest

    - name: Create env file
      run: |
        touch .env
        echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
        echo RPC_URL=${{ secrets.RPC_URL }} >> .env

    - uses: HatsuneMiku3939/direnv-action@v1
    - name: Start containers
      run: docker-compose -f "docker-compose-ci.yml" up --build --remove-orphans --force-recreate --exit-code-from agent

    - name: Check running agent
      run: docker inspect bsp-agent

    - name: Check running containers
      run: docker ps

    - name: Delete env file
      run: |
        rm -rf .env

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down
  
  build-elrond:
    runs-on: ubuntu-latest
    env:
      BLOCKCHAIN: elrond
    steps:
    - name: Login to GitHub Container Registry
      if: ${{ !env.ACT }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}

    - uses: actions/checkout@v2
    - name: Build & Publish the Docker image
      if: ${{ !env.ACT }}
      run: |
        docker build . --file Dockerfile --tag ghcr.io/covalenthq/bsp-agent:latest
        docker push ghcr.io/covalenthq/bsp-agent:latest

    - name: Create env file
      run: |
        touch .env
        echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
        echo RPC_URL=${{ secrets.RPC_URL }} >> .env

    - uses: HatsuneMiku3939/direnv-action@v1
    - name: Start containers
      run: docker-compose -f "docker-compose-ci.yml" up --build --remove-orphans --force-recreate --exit-code-from agent

    - name: Check running agent
      run: docker inspect bsp-agent

    - name: Check running containers
      run: docker ps

    - name: Delete Env file
      run: |
        rm -rf .env

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down

